In [4]:
import pandas as pd
import yfinance as yf
import numpy as np

In [49]:
nflx = yf.Ticker("NFLX")

In [24]:
nflx.info

{'address1': '121 Albright Way',
 'city': 'Los Gatos',
 'state': 'CA',
 'zip': '95032',
 'country': 'United States',
 'phone': '408 540 3700',
 'website': 'https://www.netflix.com',
 'industry': 'Entertainment',
 'industryDisp': 'Entertainment',
 'sector': 'Communication Services',
 'sectorDisp': 'Communication Services',
 'longBusinessSummary': 'Netflix, Inc. provides entertainment services. It offers TV series, documentaries, feature films, and mobile games across various genres and languages. The company provides members the ability to receive streaming content through a host of internet-connected devices, including TVs, digital video players, television set-top boxes, and mobile devices. The company has approximately 231 million paid members in 190 countries. Netflix, Inc. was incorporated in 1997 and is headquartered in Los Gatos, California.',
 'fullTimeEmployees': 12800,
 'companyOfficers': [{'maxAge': 1,
   'name': 'Mr. Wilmot Reed Hastings Jr.',
   'age': 62,
   'title': 'Co-Founder & Exec. Chairman',
   'yearBorn': 1960,
   'fiscalYear': 2022,
   'totalPay': 1665055,
   'exercisedValue': 0,
   'unexercisedValue': 334580480},
  {'maxAge': 1,
   'name': 'Mr. Theodore A. Sarandos',
   'age': 57,
   'title': 'Co-CEO, Pres & Director',
   'yearBorn': 1965,
   'fiscalYear': 2022,
   'totalPay': 21786777,
   'exercisedValue': 0,
   'unexercisedValue': 66233184},
  {'maxAge': 1,
   'name': 'Mr. Gregory K. Peters',
   'age': 51,
   'title': 'Co-CEO, Pres & Director',
   'yearBorn': 1971,
   'fiscalYear': 2022,
   'totalPay': 16617263,
   'exercisedValue': 0,
   'unexercisedValue': 18260940},
  {'maxAge': 1,
   'name': 'Mr. Spencer Adam Neumann',
   'age': 52,
   'title': 'Chief Financial Officer',
   'yearBorn': 1970,
   'fiscalYear': 2022,
   'totalPay': 7038537,
   'exercisedValue': 0,
   'unexercisedValue': 3782964},
  {'maxAge': 1,
   'name': 'Mr. David  Hyman',
   'age': 56,
   'title': 'Chief Legal Officer & Sec.',
   'yearBorn': 1966,
   'fiscalYear': 2022,
   'totalPay': 6012971,
   'exercisedValue': 0,
   'unexercisedValue': 18886556},
  {'maxAge': 1,
   'name': 'Ms. Rachel  Whetstone',
   'age': 54,
   'title': 'Chief Communications Officer',
   'yearBorn': 1968,
   'fiscalYear': 2022,
   'totalPay': 5502799,
   'exercisedValue': 0,
   'unexercisedValue': 533586},
  {'maxAge': 1,
   'name': 'Mr. Jeffrey William Karbowski',
   'age': 43,
   'title': 'VP, Chief Accounting Officer & Principal Accounting Officer',
   'yearBorn': 1979,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Mr. Spencer  Wang',
   'title': 'VP of Fin., Corp. Devel. & Investor Relations',
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Ms. Marian  Lee',
   'age': 43,
   'title': 'Chief Marketing Officer',
   'yearBorn': 1979,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Ms. Bela  Bajaria',
   'title': 'Chief Content Officer',
   'exercisedValue': 0,
   'unexercisedValue': 0}],
 'auditRisk': 10,
 'boardRisk': 10,
 'compensationRisk': 10,
 'shareHolderRightsRisk': 6,
 'overallRisk': 10,
 'governanceEpochDate': 1693526400,
 'compensationAsOfEpochDate': 1672444800,
 'maxAge': 86400,
 'priceHint': 2,
 'previousClose': 442.8,
 'open': 443.07,
 'dayLow': 443.04,
 'dayHigh': 449.89,
 'regularMarketPreviousClose': 442.8,
 'regularMarketOpen': 443.07,
 'regularMarketDayLow': 443.04,
 'regularMarketDayHigh': 449.89,
 'payoutRatio': 0.0,
 'beta': 1.286307,
 'trailingPE': 47.772255,
 'forwardPE': 28.843042,
 'volume': 1163247,
 'regularMarketVolume': 1163247,
 'averageVolume': 6259638,
 'averageVolume10days': 4066510,
 'averageDailyVolume10Day': 4066510,
 'bid': 443.2,
 'ask': 443.33,
 'bidSize': 800,
 'askSize': 1100,
 'marketCap': 197093933056,
 'fiftyTwoWeekLow': 211.73,
 'fiftyTwoWeekHigh': 485.0,
 'priceToSalesTrailing12Months': 6.1349435,
 'fiftyDayAverage': 432.978,
 'twoHundredDayAverage': 362.46634,
 'trailingAnnualDividendRate': 0.0,
 'trailingAnnualDividendYield': 0.0,
 'currency': 'USD',
 'enterpriseValue': 204642091008,
 'profitMargins': 0.13217,
 'floatShares': 437221879,
 'sharesOutstanding': 443147008,
 'sharesShort': 8396539,
 'sharesShortPriorMonth': 9055028,
 'sharesShortPreviousMonthDate': 1689292800,
 'dateShortInterest': 1692057600,
 'sharesPercentSharesOut': 0.0189,
 'heldPercentInsiders': 0.01349,
 'heldPercentInstitutions': 0.83879995,
 'shortRatio': 1.07,
 'shortPercentOfFloat': 0.019199999,
 'impliedSharesOutstanding': 443147008,
 'bookValue': 51.523,
 'priceToBook': 8.632256,
 'lastFiscalYearEnd': 1672444800,
 'nextFiscalYearEnd': 1703980800,
 'mostRecentQuarter': 1688083200,
 'earningsQuarterlyGrowth': 0.032,
 'netIncomeToCommon': 4246256128,
 'trailingEps': 9.31,
 'forwardEps': 15.42,
 'pegRatio': 1.54,
 'lastSplitFactor': '7:1',
 'lastSplitDate': 1436918400,
 'enterpriseToRevenue': 6.37,
 'enterpriseToEbitda': 34.206,
 '52WeekChange': 0.872067,
 'SandP52WeekChange': 0.08443928,
 'exchange': 'NMS',
 'quoteType': 'EQUITY',
 'symbol': 'NFLX',
 'underlyingSymbol': 'NFLX',
 'shortName': 'Netflix, Inc.',
 'longName': 'Netflix, Inc.',
 'firstTradeDateEpochUtc': 1022160600,
 'timeZoneFullName': 'America/New_York',
 'timeZoneShortName': 'EDT',
 'uuid': '1a1cddac-4d41-374d-b202-739314177b67',
 'messageBoardId': 'finmb_32012',
 'gmtOffSetMilliseconds': -14400000,
 'currentPrice': 444.7597,
 'targetHighPrice': 600.0,
 'targetLowPrice': 293.0,
 'targetMeanPrice': 463.43,
 'targetMedianPrice': 490.0,
 'recommendationMean': 2.2,
 'recommendationKey': 'buy',
 'numberOfAnalystOpinions': 37,
 'totalCash': 8576989184,
 'totalCashPerShare': 19.355,
 'ebitda': 5982716928,
 'totalDebt': 16993690624,
 'quickRatio': 1.129,
 'currentRatio': 1.326,
 'totalRevenue': 32126445568,
 'debtToEquity': 74.428,
 'revenuePerShare': 72.226,
 'returnOnAssets': 0.07235,
 'returnOnEquity': 0.20265,
 'grossProfits': 12447265000,
 'freeCashflow': 17861232640,
 'operatingCashflow': 4619639808,
 'earningsGrowth': 0.028,
 'revenueGrowth': 0.027,
 'grossMargins': 0.38773,
 'ebitdaMargins': 0.18621999,
 'operatingMargins': 0.17507,
 'financialCurrency': 'USD',
 'trailingPegRatio': 1.6243}

In [ ]:
#Learn what is a risk analysis and how to compute it

In [2]:
Stocks = ["NFLX","TSLA","GOOG"]
Start = "2013-01-01"
End = "2023-01-01"

Data = yf.download(Stocks, start= Start, end= End)

[*********************100%%**********************]  3 of 3 completed

In [5]:
Data.info()
Copy = Data['Close']

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 2518 entries, 2013-01-02 to 2022-12-30
Data columns (total 18 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   (Adj Close, GOOG)  2518 non-null   float64
 1   (Adj Close, NFLX)  2518 non-null   float64
 2   (Adj Close, TSLA)  2518 non-null   float64
 3   (Close, GOOG)      2518 non-null   float64
 4   (Close, NFLX)      2518 non-null   float64
 5   (Close, TSLA)      2518 non-null   float64
 6   (High, GOOG)       2518 non-null   float64
 7   (High, NFLX)       2518 non-null   float64
 8   (High, TSLA)       2518 non-null   float64
 9   (Low, GOOG)        2518 non-null   float64
 10  (Low, NFLX)        2518 non-null   float64
 11  (Low, TSLA)        2518 non-null   float64
 12  (Open, GOOG)       2518 non-null   float64
 13  (Open, NFLX)       2518 non-null   float64
 14  (Open, TSLA)       2518 non-null   float64
 15  (Volume, GOOG)     2518 non-null   int64
 16  (Volume, NFLX)     2518 non-null   int64
 17  (Volume, TSLA)     2518 non-null   int64
dtypes: float64(15), int64(3)
memory usage: 373.8 KB

In [43]:
#Copy = Copy.transpose()

In [45]:
Copy.info()

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 2518 entries, 2013-01-02 to 2022-12-30
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   GOOG    2518 non-null   float64
 1   NFLX    2518 non-null   float64
 2   TSLA    2518 non-null   float64
dtypes: float64(3)
memory usage: 143.2 KB

In [41]:
Copy.describe()

              GOOG         NFLX         TSLA
count  2518.000000  2518.000000  2518.000000
mean     59.315665   239.053170    73.102271
std      35.169357   174.233526   101.969056
min      17.506132    13.144286     2.194000
25%      29.984361    89.404287    14.544000
50%      51.419500   190.705002    18.954333
75%      73.789251   361.797501    79.093498
max     150.709000   691.690002   409.970001

In [47]:
Copy

                 GOOG        NFLX        TSLA
Date
2013-01-02  18.013729   13.144286    2.357333
2013-01-03  18.024191   13.798571    2.318000
2013-01-04  18.380356   13.711429    2.293333
2013-01-07  18.300158   14.171429    2.289333
2013-01-08  18.264042   13.880000    2.245333
...               ...         ...         ...
2022-12-23  89.809998  294.959991  123.150002
2022-12-27  87.930000  284.170013  109.099998
2022-12-28  86.459999  276.880005  112.709999
2022-12-29  88.949997  291.119995  121.820000
2022-12-30  88.730003  294.880005  123.180000

[2518 rows x 3 columns]

In [9]:

GOOG_dailies = Copy['GOOG'].pct_change().dropna()
GOOG_STD = GOOG_dailies.std()
GOOG_AV = GOOG_STD * np.sqrt(252)




NFLX_dailies = Copy['NFLX'].pct_change().dropna()
NFLX_STD = NFLX_dailies.std()
NFLX_AV = NFLX_STD * np.sqrt(252)




TSLA_dailies = Copy['TSLA'].pct_change().dropna()
TSLA_STD = TSLA_dailies.std()
TSLA_AV = TSLA_STD * np.sqrt(252)
print(f"Annualized Volatility for GOOG: {GOOG_AV:.2%}, for NFLX: {NFLX_AV:.2%},for TSLA: {TSLA_AV:.2%}")

Annualized Volatility for GOOG: 27.11%, for NFLX: 47.76%,for TSLA: 57.18%

In [10]:
def calculate_annualized_volatility(stock_data):
    dailies = stock_data.pct_change().dropna()
    std_dev = dailies.std()
    annualized_volatility = std_dev * np.sqrt(252)
    return annualized_volatility

volatilities = {}
for stock in Stocks:
    volatilities[stock] = calculate_annualized_volatility(Copy[stock])

for stock, volatility in volatilities.items():
    print(f"Annualized Volatility for {stock}: {volatility:.2%}")

Annualized Volatility for NFLX: 47.76%
Annualized Volatility for TSLA: 57.18%
Annualized Volatility for GOOG: 27.11%